Add PBKDF2 support
malept/rust-commoncrypto pull request #1
Opened 2016-12-25 00:48 UTC by carlosmn

The tests come from [RFC6070](https://tools.ietf.org/html/rfc6070) which only cover SHA-1 but it should be good enough to notice that we get the expected results.

I'm not entirely sure about the best way to return the derived key. Passing a `&mut [u8]` as a last param, essentially what we do in C, would let us know the place where to store the derived key and the user's expected length in a single parameter. While returning the `Result<Vec<u8>>` feels more like what one would expect from a rust function, but it makes us ask for the length explicitly and forces a small dynamic allocation.

Let me know if you feel strongly in either direction.

The `pbkdf2_16777216` test function takes a few seconds to run due to the number of rounds. This is part of the test vectors, but it takes significantly more time to run than the rest of the test suite, so that's something that might be worth removing since we're trusting the underlying implementation to be tested to be correct anyway, we just want to know that a few different parameters are converted correctly.

2016-12-25 00:54 UTC, malept requested changes
Thanks for the pull request! Due to the holidays, it might be a while before I look into it too deeply. But in the meantime:

2016-12-25 00:54 UTC, malept commented on NEWS.md
> +- Add support for the PBKDF2 key-derivation function.
```markdown
### Added

* Support for the PBKDF2 key-derivation function (#1)
```

2016-12-26 16:51 UTC, malept commented on NEWS.md
> +- Add support for the PBKDF2 key-derivation function.
Still missing the subheading (per http://keepachangelog.com/en/0.3.0/)

2016-12-27 21:26 UTC, carlosmn commented on NEWS.md
> +- Add support for the PBKDF2 key-derivation function.
Oops, indeed. It should be OK now.

2017-01-24 06:22 UTC, malept approved these changes
Again, thanks for the contribution! Sorry about the delay in reviewing.

I got rid of a bunch of the tests based on what you said. Also, I fixed up the docs to be a bit more consistent and ran `cargo fmt` on the files you added.

Regarding how to return the derived key, I'm more inclined to go the `Result<Vec<u8>>` route.

2017-01-24 06:22 UTC, merged